spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 5000


logging:
  level:
    org.springframework.boot: debug
    org.mybatis.example: trace

token:
  expiration-time: 14400
  refresh-expiration-time: 28800
  issuer: http://woojeong.or.kr
  signing-key: UlsanWoojeong

naver-api:
  client-id: fyti1ssu8d
  client-secret: tjDLsh5FSgUGLZRQChd0gXZhFfFRaSAGdjw3LlZ9

data-root: /Users/kohyunmin/Documents/_Currents/CheckingManager/statics/appdata/
data-url-root: /appdata


